### ISSUE TITLE
Problems with `JAddObjectToObject()`

### ISSUE THREAD

**Issue by beegee-tokyo** [blues/note-arduino#106]
Maybe it is an misunderstanding on my side how to use `JAddObjectToObject()`, but I have problems to use it.

How:
I create an object for a file. I add several values (float and integer) to it and then I add another object with additional items in it.

Result:
The values in the sub-level object are not filled correct, Zero values are missing and a float is converted to an integer.
 
Code (reduced):
```cpp
J *req = notecard.newRequest(request_name.c_str());
J *body = JCreateObject();
// Add some items on the top level
JAddStringToObject(body, value_name[sens_idx].c_str(), node_id_str);
JAddNumberToObject(body, sens_full_name.c_str(), float_val1);

// Create sub-level object and add items
J *sec_lvl = JAddObjectToObject(body, sens_full_name.c_str());

float float_val1 = 14.421384f;
float float_val1 = 121.007041f;
float float_val1 = 0.0f;

JAddNumberToObject(sec_lvl, "Lat", float_val1);
JAddNumberToObject(sec_lvl, "Lng", float_val2);
AddNumberToObject(sec_lvl, "Alt", float_val3);

// Add some more items to top level (float_val1 to float_val3 are the same than in the sub level object
JAddNumberToObject(body, "alt_10", float_val3);
JAddNumberToObject(body, "lat_10", float_val1);
JAddNumberToObject(body, "lng_10", float_val2);

JAddItemToObject(req, "body", body);

J *rsp = notecard.requestAndResponse(req);

/** Response is: 
Card request = {"req":"note.add","file":"sensors.qo","sync":true,"body":{"gps_10":{"Lat":14.42138481140137,"Lng":121.0070419311523,"Alt":0},"alt_10":0,"lat_10":14.42138481140137,"lng_10":121.0070419311523,"voltage_1":4.260000228881836,"humidity_6":51,"temperature_7":32.29999923706055,"barometer_8":1004.200012207031,"node_id":"FE08E887"},"payload":"CokA3A2JBzZrwAAAAAF0AaoGaGYHZwFDCHMnOgD//gjohw=="}
**/
```

Checking the float_val1, float_val2 and float_val3 values with a Serial.printf:
```cpp
Serial.printf("lat %.4f lng %.4f alt %.4f\n", float_val1, float_val2, float_val3);
```
results in
```log
lat 14.421385 lng 121.007042 alt 0.000000
```

In the response from the NoteCard I see the correct fields and values.
But in the NoteHub.IO I am receiving
```log
{
    "barometer_8": 1004,
    "gps_10": {
        "Lat": 14.421875,
        "Lng": 121
    },
    "humidity_6": 52,
    "lat_10": 14.421875,
    "lng_10": 121,
    "node_id": "FE08E887",
    "temperature_7": 32.6875,
    "voltage_1": 3.7597656
}
```

gps_10 ==> Lng is converted to an integer value
lng_10 ==> seems to be a float, but is missing the digits

**Comment by zfields** [comment]
`note_id` is not in the `body` of your template.

When I have a complex template, I normally add in one field at a time, and then validate. It keeps it simple, and prevents you from missing one field, which will through your template off.

_P.S. Sorry it took so long to respond. For more immediate responses, be sure to use our forum at https://discuss.blues.io._

**Comment by beegee-tokyo** [comment]
@zfields 

Thanks! I changed the structure and forgot to update the template.
Good tip with doing it one by one.
